/**
 * Work Order 3, Task 3 - the JS engine must agree with the Python one exactly.
 *
 * Fixtures are generated by scripts/export_engine_fixtures.py straight out of
 * src/dnd2024/pathing.py: the ten hand-traced cases from tests/test_pathing.py,
 * a 2,340-query sweep over every zone, four allocation traces (which catch
 * cache-invalidation drift), and the chassis table. Nothing here is hand-written
 * expected output - it is the Python engine's own answers.
 *
 *   node --test web/tests
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { PathEngine, PlayerState } from '../src/core/engine.js';

const here = dirname(fileURLToPath(import.meta.url));
const graph = JSON.parse(readFileSync(join(here, '../public/data/graph.v2.json'), 'utf8'));
const fixtures = JSON.parse(readFileSync(join(here, 'fixtures/engine_cases.json'), 'utf8'));

const engine = new PathEngine(graph);

/** The engine result, reduced to the fields the Python fixture records. */
function compare(result) {
  return {
    affordable: result.affordable,
    total_cost: result.total_cost,
    path: result.path,
    reason: result.reason,
    blocking_prereqs: result.blocking_prereqs || [],
  };
}

function stateFrom(caseData) {
  const state = engine.startState(caseData.home_zone, caseData.budget ?? fixtures.budget);
  if (caseData.owned_before) {
    state.owned = new Set(caseData.owned_before);
    state.touch();
  }
  return state;
}

test('fixtures match the graph the app ships', () => {
  assert.equal(graph.nodes.length, fixtures.graph_node_count);
  assert.equal(graph.meta.point_economy.total_points_at_level_20, fixtures.budget);
});

test('the ten hand-traced cases from the Python suite', async (t) => {
  for (const caseData of fixtures.named_cases) {
    await t.test(`${caseData.name} (${caseData.home_zone} -> ${caseData.target})`, () => {
      const state = stateFrom(caseData);
      assert.deepEqual(compare(engine.canAfford(state, caseData.target)), caseData.expected);
    });
  }
});

test('2,340-query sweep: every zone against a spread of targets', () => {
  /** @type {Map<string, PlayerState>} */
  const states = new Map();
  let checked = 0;
  const mismatches = [];

  for (const entry of fixtures.sweep) {
    let state = states.get(entry.home_zone);
    if (!state) {
      state = engine.startState(entry.home_zone, fixtures.budget);
      states.set(entry.home_zone, state);
    }
    const actual = compare(engine.canAfford(state, entry.target));
    checked += 1;
    try {
      assert.deepEqual(actual, entry.expected);
    } catch {
      mismatches.push({ ...entry, actual });
    }
  }

  assert.equal(checked, fixtures.sweep.length);
  assert.deepEqual(
    mismatches.slice(0, 3),
    [],
    `${mismatches.length}/${checked} queries diverged from the Python engine`,
  );
});

test('allocation traces: state evolves identically', async (t) => {
  for (const trace of fixtures.allocation_traces) {
    await t.test(`${trace.home_zone} build-out`, () => {
      const state = engine.startState(trace.home_zone, fixtures.budget);
      for (const step of trace.steps) {
        assert.deepEqual(
          compare(engine.canAfford(state, step.target)),
          step.preview,
          `preview diverged before allocating ${step.target}`,
        );
        engine.allocate(state, step.target);
        assert.equal(
          state.pointsSpent,
          step.points_spent_after,
          `points diverged after allocating ${step.target}`,
        );
        assert.deepEqual(
          [...state.owned].sort(),
          step.owned_after,
          `owned set diverged after allocating ${step.target}`,
        );
      }
    });
  }
});

test('chassis matches the Python engine for every zone', () => {
  for (const [zone, expected] of Object.entries(fixtures.chassis_by_zone)) {
    const state = engine.startState(zone, fixtures.budget);
    assert.deepEqual(engine.chassis(state), expected.chassis, zone);
    assert.deepEqual(engine.hitDie(state), expected.hit_die, zone);
    assert.deepEqual(engine.savingThrowProficiencies(state), expected.saving_throws, zone);
    assert.deepEqual(engine.weaponProficiencies(state), expected.weapons, zone);
  }
});

test('reference edges are excluded from the traversable graph', () => {
  const references = graph.edges.filter((edge) => edge.traversable === false);
  assert.ok(references.length > 0, 'no reference edges in the graph at all');
  for (const edge of references) {
    assert.ok(
      !engine.adjacency.get(edge.from).includes(edge.to),
      `${edge.from} -> ${edge.to} leaked into the pathing graph`,
    );
  }
});

test('the search cache does not go stale across mutations', () => {
  const state = engine.startState('Wizard', fixtures.budget);
  const before = engine.canAfford(state, 'cf_fighter_extra_attack_5');
  engine.allocate(state, 'gate_fighter');
  const after = engine.canAfford(state, 'cf_fighter_extra_attack_5');
  assert.equal(after.total_cost, before.total_cost - 1);
  assert.ok(after.path.length <= before.path.length);
});
